FROM node:alpine
COPY /client/package.json .
#RUN npm install styled-components
RUN apk update && apk add bash
RUN npm install
COPY /client/. .
#CMD ["npm", "install", "styled-components"]
#CMD ["npm", "start"]

COPY /client/script.sh /
CMD ["/bin/bash", "/script.sh"]