version: '3.8'
services:
  tts-converter-site:
    image: localhost/djelu/tts_converter_site
    build:
      dockerfile: Dockerfile.dev
    container_name: tts-converter-site-container
    volumes:
      - './client:/client'
      - 'node_modules:/client/node_modules/'
    ports:
      - '3030:3000'
    environment:
      - NODE_ENV=development
volumes:
  node_modules: