version: '3.7'

services:
  tts-converter-site:
    container_name: tts-converter-site
    image: djelu/tts_converter_site
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true