name: Build and deploy Docker container

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

#      - name: Build Docker image
#        run: docker build -f Dockerfile.prod -t djelu/tts_converter_site .
#      - name: Push Docker image
#        run: docker push djelu/tts_converter_site && docker push djelu/tts_converter_site:latest


      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: djelu/tts_converter_site
          registry: docker.io
          dockerfile: client/Dockerfile.prod
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo apt-get update && sudo apt-get install -y curl
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            su user1
            docker pull djelu/tts_converter_site:latest
            cd /home/user1/services/tts_converter_site
            docker-compose -f ./docker-compose.yaml -f ./docker-compose.prod.yaml up

#      - name: Install Docker Compose
#        run: |
#          sudo apt-get update && sudo apt-get install -y curl
#          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#          sudo chmod +x /usr/local/bin/docker-compose
#
#      - name: Start Docker Compose
#        run: docker-compose -f ./docker-compose.yaml -f ./docker-compose.prod.yaml up -d

