name: Build and deploy Docker container

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -f client/Dockerfile.dev -t djelu/tts_converter_site .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        run: docker push djelu/tts_converter_site
      - name: Install Docker Compose
        run: |
          sudo apt-get update && sudo apt-get install -y curl
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Start Docker Compose
        run: docker-compose -f ./docker-compose.yaml -f ./docker-compose.dev.yaml up -d
